discord:
  token: ${discord.secret.token:undefined}

jingle-bot:
  command-prefix: ${bot.command.prefix:>}
     
---

spring:
  profiles:
    active: default, local
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    
---

spring:
  profiles:
    active: prod
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
